// Code Generated by Sidekick is for learning and experimentation purposes only.
import React, { useState } from 'react';

const TabsNavigation = () => {
  const [tab, setTab] = useState('Home');

  const handleClick = (newTab) => {
    setTab(newTab);
  };

  const centerStyle = {
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    justifyContent: "center",
    height: "100vh",
  };

  const tabsRowStyle = {
    display: "flex",
    flexDirection: "row",
    gap: "5px", // רווח בין הכפתורים
    marginBottom: "20px"
  };

  function renderContent() {
    if (tab === 'Home') {
      return <p>Welcome to Home page</p>;
    } else if (tab === 'About') {
      return <p>Information here</p>;
    } else {
      return <p>Contact us</p>;
    }
  }

  return (
    <div style={centerStyle}>
      <div style={tabsRowStyle}>
        <button onClick={() => handleClick('Home')}>🏠 Home</button>
        <button onClick={() => handleClick('About')}>ℹ️ About</button>
        <button onClick={() => handleClick('Contact')}>📞 Contact</button>
      </div>
      <div>
        {renderContent()}
      </div>
    </div>
  );
};

export default TabsNavigation;




