// Code Generated by Sidekick is for learning and experimentation purposes only.
import React from "react"; // מייבא את React

function UserList({ users, removeUser }) { // קומפוננטה שמקבלת את רשימת המשתמשים ואת פונקציית ההסרה מהאב
    return (
        <ul>
            {users.map((user, index) => ( // עובר על כל המשתמשים במערך users
                <li key={index}>
                    {user} {/* מציג את שם המשתמש */}
                    <button onClick={() => removeUser(user)}>הסר</button> {/* כפתור שמסיר את המשתמש בלחיצה */}
                </li>
            ))}
        </ul>
    );
}

export default UserList; // ייצוא הקומפוננטה לשימוש בקובץ אחר

