// Code Generated by Sidekick is for learning and experimentation purposes only.
import React, { useState } from "react"; // מייבא את React ואת הפונקציה useState

function UserForm({ addUser }) { // קומפוננטה שמקבלת prop בשם addUser מהאב
    const [name, setName] = useState(""); // יוצר state בשם name ואת הפונקציה setName, ערך התחלתי ריק

    const handleSubmit = (e) => { // פונקציה שמופעלת כאשר שולחים את הטופס
        e.preventDefault(); // מונעת רענון של הדף
        if (name.trim()) { // בודקת אם הוזן שם (לא ריק)
            addUser(name); // קוראת לפונקציה addUser מהאב ומוסיפה את השם
            setName(""); // מאפסת את השדה
        }
    };

    return (
        <form onSubmit={handleSubmit}> {/* טופס שמאזין לאירוע שליחה */}
            <input
                type="text"
                value={name} // ערך השדה הוא ה-state
                onChange={(e) => setName(e.target.value)} // עדכון ה-state בכל שינוי בשדה
                placeholder="הכנס שם"
            />
            <button type="submit">הוסף משתמש</button> {/* כפתור לשליחת הטופס */}
        </form>
    );
}

export default UserForm; // ייצוא הקומפוננטה לשימוש בקובץ אחר


